
before:
  hooks:
    - make test
builds:
  - dir: ./task/fun
    main: .
    id: "fun"
    binary: "optimus-fun_{{.Os}}_{{.Arch}}"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Image=ghcr.io/sumitagrawal03071989/optimus-task-fun-executor
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sumitagrawal03071989/optimus-task-fun-executor:latest"
      - "ghcr.io/sumitagrawal03071989/optimus-task-fun-executor:{{ .Version }}"
    dockerfile: ./task/fun/executor/Dockerfile
    extra_files:
      - task/fun/executor

brews:
  - name: optimus-plugins-fun
    install: |
      bin.install Dir["optimus-*"]
    tap:
      owner: sumitagrawal03071989
      name: homebrew-taps
    license: "Apache 2.0"
    description: "Optimus plugins - [Optimus Fun Generator]"
    commit_author:
      name: Sumit Agrawal
      email: sumitagrawa.03071989@gmail.com